export const GET_ROOMS_DATA_LOADING ='GET_ROOMS_DATA_LOADING';
export const GET_ROOMS_DATA_SUCCESS ='GET_ROOMS_DATA_SUCCESS';
export const GET_ROOMS_DATA_FAILED ='GET_ROOMS_DATA_FAILED';

export const SET_ROOM_DATA_LOADING = 'SET_ROOM_DATA_LOADING';
export const SET_ROOM_DATA_SUCCESS = 'SET_ROOM_DATA_SUCCESS';
export const SET_ROOM_DATA_FAILED = 'SET_ROOM_DATA_FAILED';

export const SELECT_ROOM_LOADING = 'SELECT_ROOM_LOADING';
export const SELECT_ROOM_SUCCESS = 'SELECT_ROOM_SUCCESS';
export const SELECT_ROOM_FAILED = 'SELECT_ROOM_FAILED';

export const SEARCH_BY_DAY_LOADING = 'SEARCH_BY_DAY_LOADING';
export const SEARCH_BY_DAY_SUCCESS = 'SEARCH_BY_DAY_SUCCESS';
export const SEARCH_BY_DAY_FAILED = 'SEARCH_BY_DAY_FAILED';
export const RESET_DETAILS_SCREEN = 'RESET_DETAILS_SCREEN';

